
import React from 'react';
import Card from '../components/ui/Card';
import TrilingualText from '../components/ui/TrilingualText';
import { useTheme } from '../theme/ThemeContext';

interface CustomPageProps {
  title: string;
}

const CustomPage: React.FC<CustomPageProps> = ({ title }) => {
  const { theme } = useTheme();

  return (
    <div className="space-y-8">
      <header>
        <TrilingualText as="h1" text={title} />
        <p className="text-lg text-foreground/70 mt-2">
          This is a custom page generated by the AI Oracle.
        </p>
      </header>
      <Card>
        <div className="text-center py-20">
          <p className="text-card-foreground/70">
            Content for this custom page can be added here.
          </p>
        </div>
      </Card>
    </div>
  );
};

export default CustomPage;
